### ISSUE TITLE
Cores e espaçamento.

### ISSUE THREAD

**Issue by ImGabe** [d4sein/Python-educativo#1]
### Cores
Colocar cores em palavras chaves destacaria melhor e passaria uma mensagem melhor.

### Espaçamento
O texto fica muito grudado e junto, dificultando a leitura e compressão do texto.

![image](https://user-images.githubusercontent.com/24387926/56464890-0b429500-63c9-11e9-850e-779a8fcbd00e.png)

**Comment by d4sein** [comment]
Bom, pra adicionar as cores eu teria que usar ANSI, e por enquanto a maioria dos usuários Windows não são capazes de rodar no CMD, portanto não estarei trabalhando nisso por enquanto.
